# Generated by Django 5.0.2 on 2024-02-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_author_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='lname',
            field=models.CharField(max_length=51, null=True),
        ),
    ]
