# Generated by Django 5.0.2 on 2024-02-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0010_country_publications_alter_address_options_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publictaions',
            field=models.ManyToManyField(related_name='akhbar', to='bookstore.publications'),
        ),
    ]
